### ISSUE TITLE
Homey virtual buttons support

### ISSUE THREAD

**Issue by raymondwigmore** [robertklep/name.klep.homekitty#14] opened 2022-12-11 07:29 UTC
The virtual buttons setup from Homey’s own possibilities are no longer to be used as flow starters: they are actual 1, 2 and long press buttons to be programmed through Apples Home app itself. Is this per design?
![16322651-CECE-4C5C-81CE-D6FFEA9AC1A0](https://user-images.githubusercontent.com/43473117/206891531-881785c3-4b04-4112-aeb7-d0ddaf2a3029.png)

**Comment by raymondwigmore** [comment] 2022-12-11 11:08
Hi Robert,
I'd love to use just one app for this, however there is a difference between a button/knop and a switch.
I used to use VD (Virtual Devices app for this) as I have a need for both. As I would like to keep thing clean, I moved the buttons/knoppen in Homey's own virtual button. However Homey's virtual switch (schakelaar) comes up as a Power outlet, rather than a switch. HomeKitty "flow starter" is a button/knop I believe. I also just checked, the button/knop of VD app is also going the same 'issue' as the one of Homey itself.
[Homey Developer Tools.pdf](https://github.com/robertklep/name.klep.homekitty/files/10202003/Homey.Developer.Tools.pdf)
![IMG_4916](https://user-images.githubusercontent.com/43473117/206900081-bdd60bc4-bd28-419a-a145-7f41596a3f48.png)
![IMG_4915](https://user-images.githubusercontent.com/43473117/206900083-2faca745-5198-4e8b-bf4e-29e035237b26.png)
![IMG_4914](https://user-images.githubusercontent.com/43473117/206900084-8af7ee99-5080-47f5-9b32-8f2d808c8b93.png)

**Comment by robertklep** [comment] 2022-12-11 11:28
> However Homey's virtual switch (schakelaar) comes up as a Power outlet, rather than a switch. HomeKitty "flow starter" is a button/knop I believe. I also just checked, the button/knop of VD app is also going the same 'issue' as the one of Homey itself.

So it's all a bit confusing.

If I understand correctly, you have created a virtual Homey button that you want to use to trigger flows, is that correct? If so, why isn't is possible to use HomeKitty's Flow Starter instead? That device is presented to Homey as a button, but it shows up as a switch in HomeKit, which is intentional (it's a switch that turns itself off when you turn it on).

The current button mapping (how HomeKitty "translates" a Homey button device to a HomeKit device) will create stateless switches, which you have to assign button presses to, just like in your last screenshot. That's not ideal and will need to be fixed, but from what I can see, you can work around it by using the Flow Starter device.

I also now understand that Homey's virtual switch is shown as a power outlet, which seems like a different issue altogether.

**Comment by raymondwigmore** [comment] 2022-12-11 11:52
OK, 2nd try in explaining.
I have a need for both "buttons/knop" and "switch/schakelaar" in the Apple "home/woning" app.

Up until now I used "buttons" for starting flows and "switches" for setting a mode or scene (state on/off)

For "buttons" I used Homey's device "virtual button". However Homey's "virtual switch" shows up as a power outlet in apples home app, hence I use a third party app, called "virtual devices" by Robert Kranenborg.

If HomeKitty would support both a "button" and a "switch" device that would be Fantastic (feature request" because I could stop using the other apps all together.

For now, HomeKitty has "broken" both Homey's and VDapp "button"functionality and Homey's "virtual switch" shows up as a power outlet, rather than a switch.

For now I can work with using HomeKitty's flow starter for "button" functionality, reprogramming my flows, and reprogramming my scenes/modes utilizing VD's "mode/switch" device.

But it seems that this is more or less a workaround for something that isn't intended to happen in HomeKitty ;-)

If you ask me what I would like love to see: having a "flow starter" button **_and_** a "scene/mode" selector in HomeKitty

**Comment by robertklep** [comment] 2022-12-11 11:55
> For now, HomeKitty has "broken" both Homey's and VDapp "button"functionality

So these worked correctly with HomeyKit before?

**Comment by raymondwigmore** [comment] 2022-12-11 11:55
option 2: have Homey's virtual devices "button" and "switch" show up properly. Button with a state "pressed" and switch "on/off"

**Comment by raymondwigmore** [comment] 2022-12-11 12:03
> > For now, HomeKitty has "broken" both Homey's and VDapp "button"functionality
> 
> 
> 
> So these worked correctly with HomeyKit before?


That is correct

**Comment by robertklep** [comment] 2022-12-11 12:10
It doesn't really make a lot of sense that those devices are shown as an outlet in HomeKit, because the only device class for which that happens is "socket" and none of your devices are using that class.

The only issue I see here that needs fixing is for devices with class "button" and capability "button".

Are you running the current test version? If not, try and see how that works: https://homey.app/nl-nl/app/name.klep.homekitty/HomeKitty/test/

**Comment by raymondwigmore** [comment] 2022-12-11 13:29
Hi Robert, I am running the latest test version as I had those duplicate switches with my lights (I am RayWay in Slack).

**Comment by robertklep** [comment] 2022-12-11 13:36
Okay, so can you show me a device (class/capabilities) that is showing up as an outlet in HomeKit? Preferably with a screenshot on what it looks like in Home too.

And if you're still running HomeyKit as well, also a device (but not a button device with button capability, as those are confirmed to be broken) that works as expected in HomeyKit but not in HomeKitty (again with Home screenshots).

I'm looking at the HomeyKit code and I don't see how it can create a button-like device ("press" rather than "on/off") in HomeKit.

**Comment by raymondwigmore** [comment] 2022-12-11 13:54
> It doesn't really make a lot of sense that those devices are shown as an outlet in HomeKit, because the only device class for which that happens is "socket" and none of your devices are using that class.
> 
> 
> 
> The only issue I see here that needs fixing is for devices with class "button" and capability "button" (but such devices also aren't presented as an outlet to HomeKit, but rather to a not very usable stateless switch).
> 
> 
> 
> Are you running the current test version? If not, try and see how that works: https://homey.app/nl-nl/app/name.klep.homekitty/HomeKitty/test/

So, I just tested Homey's own "Virtuele Schakelaar" and you are correct: Athom has given it a device class "socket" capabilities are onoff and the driver it uses is: homey:manager:vdevice - virtual_socket

For Homey's own "Virtuele Knop" they use class "button" capabilities ID "button" and driver homey:manager:vdevice - virtual_button

Arjan Kranenburg's VD app has 2 Virtual Devices : apparaat (where I can select knop; that becomes a button, but has the same issue as Homey's "button" in HomeKitty) and a device called "mode" which becomes an actual Virtual OnOff switch in HomeKitty; he uses a device class "other" for it with onoff capabilities.

The issue I have is that both "button" options of Homey as the VD app, show up as mentioned before. For now I can resolve these with reprogramming my flows and use your "flow starter" button.

A feature request would be to add an additional device in HomeKitty being a real onoff switch, perhaps like using VD app's device class "other"?

That way I have it all in your app, and as well it follows a bit apples design thinking. Having apples "automations" -> flow starter
and having "scenes" being a state/mode by an OnOff switch

Just some thoughts

**Comment by robertklep** [comment] 2022-12-11 14:02
> The issue I have is that both "button" options of Homey as the VD app, show up as mentioned before

AFAIK, it's not possible to create buttons in HomeKit, that's why the Flow Starter looks like a switch and not a button (to mimic the statelessness of a button, it's a switch that automatically switches itself off).

> A feature request would be to add an additional device in HomeKitty being a real onoff switch, perhaps like using VD app's device class "other"?

I'm reluctant to add additional devices to HomeKitty that can easily be created with other apps, like VD. The reason the Flow Starter device exists is because a lot of users _only_ use VD to create devices that can be used to start flows using Siri.

At some point I want to implement a generic HomeKit device (one where you can choose how it appears in HomeKit), but for now I'm too busy working on getting the basics to work.

**Comment by raymondwigmore** [comment] 2022-12-11 14:08
> Okay, so can you show me a device (class/capabilities) that is showing up as an outlet in HomeKit? Preferably with a screenshot on what it looks like in Home too.
> 
> And if you're still running HomeyKit as well, also a device (but not a button device with button capability, as those are confirmed to be broken) that works as expected in HomeyKit but not in HomeKitty (again with Home screenshots).
> 
> I'm looking at the HomeyKit code and I don't see how it can create a button-like device ("press" rather than "on/off") in HomeKit.

This is Homey's implementation of a "virtual schakelaar" that shows up as a socket....
<img width="1067" alt="Scherm­afbeelding 2022-12-11 om 15 06 04" src="https://user-images.githubusercontent.com/43473117/206908522-0e88b287-52b6-4201-aad6-2ccd0230e4a2.png">
<img width="1067" alt="Scherm­afbeelding 2022-12-11 om 15 06 13" src="https://user-images.githubusercontent.com/43473117/206908528-ebbeafb0-2dc3-4435-8539-c454456f3cbc.png">

**Comment by robertklep** [comment] 2022-12-11 14:10
> This is Homey's implementation of a "virtual schakelaar" that shows up as a socket....

"Class: socket" 😅

**Comment by raymondwigmore** [comment] 2022-12-11 14:14
> > Okay, so can you show me a device (class/capabilities) that is showing up as an outlet in HomeKit? Preferably with a screenshot on what it looks like in Home too.
> > And if you're still running HomeyKit as well, also a device (but not a button device with button capability, as those are confirmed to be broken) that works as expected in HomeyKit but not in HomeKitty (again with Home screenshots).
> > I'm looking at the HomeyKit code and I don't see how it can create a button-like device ("press" rather than "on/off") in HomeKit.
> 
> This is Homey's implementation of a "virtual schakelaar" that shows up as a socket.... <img alt="Scherm­afbeelding 2022-12-11 om 15 06 04" width="1067" src="https://user-images.githubusercontent.com/43473117/206908522-0e88b287-52b6-4201-aad6-2ccd0230e4a2.png"> <img alt="Scherm­afbeelding 2022-12-11 om 15 06 13" width="1067" src="https://user-images.githubusercontent.com/43473117/206908528-ebbeafb0-2dc3-4435-8539-c454456f3cbc.png">

unfortunately I no longer have HomeyKit running, because that version was working with both push button options from either Homey itself or the "virtual devices" app.  I am happy to use "flow starter" as a push button option and continue to work with the VDapp for real "OnOff" schakelaars.

I was only trying to help out, pointing out that HomeKitty has broken something that was working perfectly in HomeyKit; push buttons by either Homey's own "virtuele knop" as for VD app's "virtuele knop" so actually there was no need for HomeKitty's "Flow Starter" except convenience of having it all in one app, so hence my feature request for adding a real "virtuele schakelaar" :-)

**Comment by raymondwigmore** [comment] 2022-12-11 14:18
So just to be clear I have provided you with what you were asking....
This is VDapps version of a "mode" switch
<img width="1067" alt="Scherm­afbeelding 2022-12-11 om 15 17 00" src="https://user-images.githubusercontent.com/43473117/206909041-95c49973-d127-43b0-8048-47bd9723c449.png">
<img width="1067" alt="Scherm­afbeelding 2022-12-11 om 15 17 13" src="https://user-images.githubusercontent.com/43473117/206909043-837ab46c-2019-4585-81ae-0ad525ba4562.png">

**Comment by raymondwigmore** [comment] 2022-12-11 14:19
> > > Okay, so can you show me a device (class/capabilities) that is showing up as an outlet in HomeKit? Preferably with a screenshot on what it looks like in Home too.
> > > And if you're still running HomeyKit as well, also a device (but not a button device with button capability, as those are confirmed to be broken) that works as expected in HomeyKit but not in HomeKitty (again with Home screenshots).
> > > I'm looking at the HomeyKit code and I don't see how it can create a button-like device ("press" rather than "on/off") in HomeKit.
> > 
> > 
> > This is Homey's implementation of a "virtual schakelaar" that shows up as a socket.... <img alt="Scherm­afbeelding 2022-12-11 om 15 06 04" width="1067" src="https://user-images.githubusercontent.com/43473117/206908522-0e88b287-52b6-4201-aad6-2ccd0230e4a2.png"> <img alt="Scherm­afbeelding 2022-12-11 om 15 06 13" width="1067" src="https://user-images.githubusercontent.com/43473117/206908528-ebbeafb0-2dc3-4435-8539-c454456f3cbc.png">
> 
> unfortunately I no longer have HomeyKit running, because that version was working with both push button options from either Homey itself or the "virtual devices" app. I am happy to use "flow starter" as a push button option and continue to work with the VDapp for real "OnOff" schakelaars.
> 
> I was only trying to help out, pointing out that HomeKitty has broken something that was working perfectly in HomeyKit; push buttons by either Homey's own "virtuele knop" as for VD app's "virtuele knop" so actually there was no need for HomeKitty's "Flow Starter" except convenience of having it all in one app, so hence my feature request for adding a real "virtuele schakelaar" :-)

This one shows up as a socket in Apples Woning app

**Comment by raymondwigmore** [comment] 2022-12-11 14:20
> So just to be clear I have provided you with what you were asking....
> This is VDapps version of a "mode" switch
> <img alt="Scherm­afbeelding 2022-12-11 om 15 17 00" width="1067" src="https://user-images.githubusercontent.com/43473117/206909041-95c49973-d127-43b0-8048-47bd9723c449.png">
> <img alt="Scherm­afbeelding 2022-12-11 om 15 17 13" width="1067" src="https://user-images.githubusercontent.com/43473117/206909043-837ab46c-2019-4585-81ae-0ad525ba4562.png">

This one shows up as a real "one-off" switch in Apple's woning app

**Comment by raymondwigmore** [comment] 2022-12-11 14:21
> > This is Homey's implementation of a "virtual schakelaar" that shows up as a socket....
> 
> "Class: socket" 😅

That's what I mentioned earlier... not sure why they did that.... That's why I use VD app's "mode" switch
works fine and continues to work fine for now.

**Comment by robertklep** [comment] 2022-12-11 14:22
Just to recap:
* A Homey device with class "socket" is going to be shown as an Outlet in HomeKit.
* A Homey device with class "button" and capability "button" is now broken in HomeKitty. In HomeyKit it's shown as a switch, and I will fix HomeKitty so it will be shown as a switch there too.

**Comment by raymondwigmore** [comment] 2022-12-11 14:25
> At some point I want to implement a generic HomeKit device (one where you can choose how it appears in HomeKit), but for now I'm too busy working on getting the basics to work.

I would love to see that happening ;-)

**Comment by raymondwigmore** [comment] 2022-12-11 14:26
> Just to recap:
> 
> * A Homey device with class "socket" is going to be shown as an Outlet in HomeKit (even if it was shown differently in HomeyKit).
> * A Homey device with class "button" and capability "button" is now broken in HomeKitty. In HomeyKit it's shown as a switch, and I will fix HomeKitty so it will be shown as a switch there too.

Yup! Correct and understood...

**Comment by robertklep** [comment] 2022-12-18 15:53
The "button" issue should be fixed in the current test version: [v1.2.0](https://homey.app/a/name.klep.homekitty/test/).

**Closed by robertklep** 2022-12-18 15:53 UTC
Labels: works in homeykit
