### ISSUE TITLE
Support Heimdall Virtual Devices

### ISSUE THREAD

**Issue by thomaswitt** [robertklep/name.klep.homekitty#54] opened 2023-06-11 14:51 UTC
(make sure you also edit the title)

### Type (brand/model) of device
Heimdall App / Heimdall Surveilance

### Homey Model
- [x] Homey Pro 2023

### Is it supported by HomeyKit?
- [x] Yes

### Device Classes
* _Class_: Sensor

### Device Capabilities
HomeKit exposed my Heimdall Alarm Status perfectly to HomeKit as virtual switch (Home,Away,Off,…), so I could sync all alarms in the Home App. Unfortunately, HomeyKitty doesn't support this Sensor Alarm Class anymore. I'd be delighted if that would return soon.

**Comment by robertklep** [comment] 2023-06-11 15:58
Which capabilities do these devices have?

**Comment by thomaswitt** [comment] 2023-06-11 16:20
It's a security system, type 55

**Comment by robertklep** [comment] 2023-06-11 18:47
Are you sure that **HomeyKit** supports these devices? Or do you mean the built-in HomeKit experiment?

**Comment by thomaswitt** [comment] 2023-06-12 07:45
100% sure. It worked fine with my old HomeyPro (2018) and the Homekit app (not the experiment!) – I had HomeKit automatization with it – , but when I migrated to the new 2023 model, I had to upgrade to HomeKitty due to SDKv3 compatibility. Therefore I lost those devices.

**Comment by robertklep** [comment] 2023-06-12 09:12
Okay, I found it, but I'm not sure what the issue is since the "Mode" device is supported by HomeKitty:

<img width="534" alt="image" src="https://github.com/robertklep/name.klep.homekitty/assets/1190916/54639f3d-842e-4ef7-8a21-6416006fd4b5">

Make sure to run the [test version](https://homey.app/a/name.klep.homekitty/test/).

**Comment by thomaswitt** [comment] 2023-06-12 09:26
Sorry, just saw your last sentence. I don't run the test version. I don't want to change it to the test version because then I'd need to recreate and reassign all my devices in HomeKit. So I guess I just have to wait until it's supported in the official version. Sorry for the confusion.

**Comment by robertklep** [comment] 2023-06-12 09:43
If you can't run the test version because you need to recreate and reassign your devices, the same will happen when the current test version is upgraded to stable.

Besides that, I fixed the issue with the Heimdall button not being supported, but that fix will be present in the test version of the app for the time being.

**Closed by robertklep** 2023-06-12 09:43 UTC

**Comment by thomaswitt** [comment] 2023-06-12 09:47
Thanks for your help!
