### ISSUE TITLE
Support for Somfy RTS devices

### ISSUE THREAD

**Issue by jhemelaers-isense-development-be** [robertklep/name.klep.homekitty#18] opened 2022-12-16 09:09 UTC
Support for Somfy RTS devices

### Type (brand/model) of device
Somfy

### Is it supported by HomeyKit?
Yes

### Device Classes

* _Class_: windowcoverings
* _Virtual Class_: sunshade

### Device Capabilities

* windowcoverings_state
* windowcoverings_tilt_down
* windowcoverings_tilt_up

**Comment by robertklep** [comment] 2022-12-18 08:22
That's is an odd combination of capabilities. I see how HomeyKit implements support for this device, but it's actually not correct.

In the Homey app, I assume you get these buttons?

![B9C6D7F7-BCBF-423A-8674-BC39A33FCB91_1_102_o](https://user-images.githubusercontent.com/1190916/208288375-b9824e76-cda4-4530-84ae-43bef224f59e.jpeg)

What exactly do they do when you press them?

**Comment by jhemelaers-isense-development-be** [comment] 2022-12-18 08:30
Hey Robert,

The button up makes the sunshade go up, down lets it go down en the middle button is for stopping it halfway or at a certain position. In the home app from apple you have the slider and not the still button. When tou touched the slider then the sunshade stops. It didn't matter at which position you set the slider. When it was just somewhere in between 0% and 100%, that triggered the stop.

That was at least how it worked via the previous komekit app ☺️.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Robert Klep ***@***.***>
Verzonden: Sunday, December 18, 2022 9:23:06 AM
Aan: robertklep/name.klep.homekitty ***@***.***>
CC: Jan Hemelaers - Isense-Development ***@***.***>; Author ***@***.***>
Onderwerp: Re: [robertklep/name.klep.homekitty] Support for Somfy RTS devices (Issue #18)


That's is an odd combination of capabilities. I see how HomeyKit implements support for this device, but it's actually not correct.

In the Homey app, I assume you get these buttons?

[B9C6D7F7-BCBF-423A-8674-BC39A33FCB91_1_102_o]<https://user-images.githubusercontent.com/1190916/208288375-b9824e76-cda4-4530-84ae-43bef224f59e.jpeg>

What exactly do they do when you press them?

**Comment by robertklep** [comment] 2022-12-18 08:33
Ah yes, that does make sense 😊 I'll try to implement it the same way as with HomeyKit.

**Comment by robertklep** [comment] 2022-12-18 14:07
I'm afraid it's going to be very difficult to implement support for this device in HomeKitty, due to the way it's implemented.

HomeyKit was riddled with workarounds for features that couldn't cleanly convert between Homey and HomeKit, like in this case. HomeKitty uses a much more structured approach, but that makes implementing these workarounds very difficult.

So for the time being, this device won't be supported directly by HomeKitty.

As a (hopefully temporary) workaround you can use the [Virtual Devices](https://homey.app/nl-nl/app/com.arjankranenburg.virtual/Virtuele-Apparaten/) app to create a virtual device (I hope you read Dutch):
* apparaatklasse "Zonnescherm"
* eigenschappen "Positie"

Such a device is supported by HomeKitty.

You also need a few flows to synchronise the state of that virtual device with the actual device.

**Comment by robertklep** [comment] 2022-12-19 09:21
After a good night's sleep, I think I found a way of dealing with this device that doesn't require a lot of workarounds.

**Comment by jhemelaers-isense-development-be** [comment] 2022-12-19 09:49
Hi Robert,

That would be great!
Of in het Nederlands: Dat zou fantastisch zijn!
Ik ben Belgisch trouwens, dus ik begreep het 😅

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Robert Klep ***@***.***>
Verzonden: Monday, December 19, 2022 10:21:14 AM
Aan: robertklep/name.klep.homekitty ***@***.***>
CC: Jan Hemelaers - Isense-Development ***@***.***>; Author ***@***.***>
Onderwerp: Re: [robertklep/name.klep.homekitty] Support for Somfy RTS devices (Issue #18)


After a good night's sleep, I think I found a way of dealing with this device that doesn't require a lot of workarounds.

**Closed** 2022-12-19 10:03 UTC

**Comment by robertklep** [comment] 2022-12-19 10:05
The current test version (v1.2.1) should now support it: https://homey.app/a/name.klep.homekitty/test/

**Comment by jhemelaers-isense-development-be** [comment] 2022-12-19 15:44
Hi Robert,

The devices can be added to the home app on ios.
They also function.
Only the status keeps spinning from the device on the dashboard. But when you open the details of the device it is the correct status.
I will add 2 screenshots:


Met



[image004.png]



Webapplication Development

Oude Baan 69B

B-2230 Herselt

Belgie



GSM: 0468/14.20.66

Email: ***@***.***

________________________________
Van: Robert Klep ***@***.***>
Verzonden: Monday, December 19, 2022 11:05:51 AM
Aan: robertklep/name.klep.homekitty ***@***.***>
CC: Jan Hemelaers - Isense-Development ***@***.***>; Author ***@***.***>
Onderwerp: Re: [robertklep/name.klep.homekitty] Support for Somfy RTS devices (Issue #18)


The current test version (v1.2.1) should now support it: https://homey.app/a/name.klep.homekitty/test/

**Comment by robertklep** [comment] 2022-12-20 06:54
There was indeed an issue, the current test version (v1.2.3) hopefully fixes it.

**Comment by jhemelaers-isense-development-be** [comment] 2022-12-20 10:56
Hi Robert,

It's still the same... i also tried to restart homeykitty and also homey itself with no luck.

Also on startup of the home app on ios all the window coverings show status: Sluiten...

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Robert Klep ***@***.***>
Verzonden: Tuesday, December 20, 2022 7:54:38 AM
Aan: robertklep/name.klep.homekitty ***@***.***>
CC: Jan Hemelaers - Isense-Development ***@***.***>; Author ***@***.***>
Onderwerp: Re: [robertklep/name.klep.homekitty] Support for Somfy RTS devices (Issue #18)


There was indeed an issue, the current test version (v1.2.3) hopefully fixes it.

**Comment by robertklep** [comment] 2022-12-20 11:05
Yes, I just spotted _another_ issue 🫣 Try the new test (v1.2.5)

**Comment by jhemelaers-isense-development-be** [comment] 2022-12-20 11:09
Hi Robert,

Fantastic! Works great! Thanks for the effort!!!

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Robert Klep ***@***.***>
Verzonden: Tuesday, December 20, 2022 12:05:49 PM
Aan: robertklep/name.klep.homekitty ***@***.***>
CC: Jan Hemelaers - Isense-Development ***@***.***>; Author ***@***.***>
Onderwerp: Re: [robertklep/name.klep.homekitty] Support for Somfy RTS devices (Issue #18)


Yes, I just spotted another issue 🫣 Try the new test (v1.2.5)

**Comment by robertklep** [comment] 2022-12-20 11:09
Thanks again 👍🏻

**Comment by robertklep** [comment] 2022-12-25 11:04
@jhemelaers-isense-development-be can you take a look at issue #26 to see if you can reproduce the same problems as mentioned there?

**Comment by jhemelaers-isense-development-be** [comment] 2022-12-25 11:14
Hi Robert,

Hi don’t have this issue, but i had it once.
What i did is i removed my bridge in the home app(ios).
I both removes the old homekit app and the new homeykitty on homey.
I started everything from scratch and now it still works.

Like i mentioned earlier, i think ther is a conflict if you just install the new homeykitty app and you also keep the old komekit app on homey.

I also updated all my ios devices to 16.2. In that version are changes related to the architecture of the home app.


Met



[image004.png]



Webapplication Development

Oude Baan 69B

B-2230 Herselt

Belgie



GSM: 0468/14.20.66

Email: ***@***.***

________________________________
Van: Robert Klep ***@***.***>
Verzonden: Sunday, December 25, 2022 12:04:40 PM
Aan: robertklep/name.klep.homekitty ***@***.***>
CC: Jan Hemelaers - Isense-Development ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [robertklep/name.klep.homekitty] Support for Somfy RTS devices (Issue #18)


@jhemelaers-isense-development-be<https://github.com/jhemelaers-isense-development-be> can you take a look at issue #26<https://github.com/robertklep/name.klep.homekitty/issues/26> to see if you can reproduce the same problems as mentioned there?

**Comment by steplein** [comment] 2023-01-08 19:29
hey robert, first of all thanks for the effort younger putting into the app. really appreciate! i had the same problem with the somfy plug-in. after deleting the old homeykit and reinstalled homeykitty everything seems to work fine. thanks again.
