### ISSUE TITLE
Eve Door and Window Displays Two Devices in HomeKit

### ISSUE THREAD

**Issue by David1-5** [robertklep/name.klep.homekitty#97] opened 2024-06-21 20:07 UTC
When Eve Door and Window is added via Matter to Homey PRO, then made available to HomeKit, two devices are added, a contact sensor and a switch. The switch cannot be removed.

Ideally only the contact sensor should be displayed. I have noticed it also happens with Zigbee sensors such as leak detectors.

I have disabled HP HK experiment which displays the sensor as a humidity sensor and that makes no difference.

I have tried with and without the Eve app installed in HP and using Home Assistant to add sensors to Homey Pro and then to HomeKit via HomeKitty. Every instance and configuration appears to result in two devices for sensors, a sensor (correct) and a switch (incorrect, I assume).

It would be good to get this sorted as adding to HomeKit and pairing with Homey Pro as a Mattrr device is u reliable in Homey Pro. The HK experiment in HP doesn’t work, and HP doesn’t support Matter pairing to add to other eco systems, so Homekitty is the only option.

**Comment by bursacmilan** [comment] 2024-08-23 14:22
I'm using the Aqara Door Sensor P2. The sensor appears also as two devices in HomeKit: a "Sensor" and a "Switch." The problem is that when I turn on the switch, the entire device gets removed from Homey, forcing me to re-pair it.

**Comment by robertklep** [comment] 2024-08-23 17:28
@bursacmilan is the device connected via Matter too? Sounds like an issue with Homey's Matter implementation, the only thing that HomeKitty does is turning on the switch.

**Comment by David1-5** [comment] 2024-08-23 20:43
Hi

No, it’s any sensor added.


David

I'm using the Aqara Door Sensor P2. The sensor appears also as two devices in HomeKit: a "Sensor" and a "Switch." The problem is that when I turn on the switch, the entire device gets removed from Homey, forcing me to re-pair it.

**Comment by robertklep** [comment] 2024-08-24 04:57
@David1-5 the [Feature Request/Unsupported Device](https://github.com/robertklep/name.klep.homekitty/issues/new?assignees=&labels=&projects=&template=feature-request-unsupported-device.md&title=%5BFeature+Request%2FUnsupported%5D) issue template is better suited for this issue, because it asks you to look up various configuration details for the device which I need to determine why it shows up as two devices.

I'll close this issue and hope you can submit a new one with that template.

**Closed by robertklep** 2024-08-24 04:57 UTC

**Comment by robertklep** [comment] 2024-08-24 18:28
Should be fixed in v2.2.18, [the current test version](https://homey.app/a/name.klep.homekitty/test/).

**Comment by David1-5** [comment] 2024-08-24 20:35
Thanks Robert

David

On 25 Aug 2024, at 04:28, Robert Klep ***@***.***> wrote:


Should be fixed in v2.2.18, the current test version <https://homey.app/a/name.klep.homekitty/test/>.
