### ISSUE TITLE
Loose configuration when Homey reboot

### ISSUE THREAD

**Issue by dokmadeinitaly** [robertklep/name.klep.homekitty#19] opened 2022-12-16 15:15 UTC
Hi Robert,
Thanks for your job!
I’m running iOS 16.2 with Home app updated and Homey last firmware.

When i reboot Homey or HomeKitty app, i loose HomeKit configuration of all virtual devices (created directly with Homey not with virtual devices app). I loose devices, automation, scene evrithing. 
I don’t loose other devices configuration created with other Homey app like switchbot or philips Hue, i loose configuration only of Homey virtual devices (all switches).

Can you help me?
Thank you!

**Comment by robertklep** [comment] 2022-12-16 15:33
I can't reproduce your problem: I tested with both a virtual switch and a virtual button, and both seem to retain their Home configuration when I restart HomeKitty or reboot my Homey.

It's also very strange that it's just _those_ devices that don't work.

Can you restart the HomeKitty app and then create a diagnostic report for it? Perhaps there's something in the log that points to a reason.

**Comment by raymondwigmore** [comment] 2022-12-20 15:16
Hi Robert,
I actually have the same issue with HomeKitty flow starter devices. They actually don't disappear, but are coming up as new devices in my default room for domotica. And as mentioned by the other user: the associated scenes do disappear, additionally I can not recreate the scenes (I think that's because somehow apples home app keeps old scenes in a file although the devices are no longer there)

**Comment by robertklep** [comment] 2022-12-20 15:22
@raymondwigmore strange. Does it always happen, or only sometimes? 

Can you make a note of the device's serial number (in the Home app, long-press the device's tile, choose Accessory Details, then scroll down to find its serial number) and check if it has changed when the device comes up as a new device?

**Comment by raymondwigmore** [comment] 2022-12-20 15:33
> @raymondwigmore strange. Does it always happen, or only sometimes? 
> 
> 
> 
> Can you make a note of the device's serial number (in the Home app, long-press the device's tile, choose Accessory Details, then scroll down to find its serial number) and check if it has changed when the device comes up as a new device?

Hi again... happens every time after a restart and/or update (which means a restart anyway). Just restarted the HoneKitty app and serial numbers and all other details remain the same

**Comment by OlivierZal** [comment] 2022-12-20 15:36
Same here:

```
[log] 2022-12-19 17:17:28 [ManagerDrivers] [Driver:flow-starter] FlowStarterDriver has been initialized
[log] 2022-12-19 17:17:28 [ManagerDrivers] [Driver:flow-starter] [Device:a5306832-5283-4ab8-ae07-e7eaabee40ad] FlowStarterDevice has been initialized
[log] 2022-12-19 17:17:28 [ManagerDrivers] [Driver:flow-starter] [Device:a5306832-5283-4ab8-ae07-e7eaabee40ad] adding to HomeKit
```

but serial number in Homey: `3bb545d0-3ec7-4bfc-9bc0-df52ff908bd6`

**Comment by robertklep** [comment] 2022-12-20 15:40
I wonder if it might have to do with the bridge coming up before the device is ready to be published. Will investigate.

**Comment by robertklep** [comment] 2022-12-20 16:23
Try v1.2.6 (current test).

**Comment by OlivierZal** [comment] 2022-12-20 16:30
I didn't notice the issue when updating HomeKitty.

**Comment by raymondwigmore** [comment] 2022-12-20 16:33
> Try v1.2.6 (current test).

Seems to resolve one of the issues: restarted app 2x, devices remain in room etc. Does not resolve the issue of recreating the scenes within Apple Hone app. It gives a generic. Can't add the scene error for scenes that o had initially created with the de ices that were dropped previously by HomeKitty. It's like they stay in some kind of buffer in HomeKit somewhere

**Comment by robertklep** [comment] 2022-12-20 16:40
@raymondwigmore you may have to delete the flow starter device and create a new one.

**Comment by raymondwigmore** [comment] 2022-12-20 17:00
> @raymondwigmore you may have to delete the flow starter device and create a new one to replace it.

Nope, checked... didn't resolve. Had the issue before also with HomeKit, after installing HomeKitty I could create the new scenes. Probably as I started with a clean slate. I created a work around for now by adding the buttons as favorites in Apple home app, rather than creating a scene with them. Not as fancy but it works... perhaps in the future you can investigate if HomeKit keeps record / breadcrumbs of old scenes that were removed after devices were removed. Could be an Apple issue ;-)

**Comment by robertklep** [comment] 2022-12-20 18:31
@raymondwigmore Home losing configuration for devices is quite common, it's really not very well implemented. That's why I don't use any automations (or scenes) with HomeKit, I'll leave that to a proper home automation platform (Home Assistant in my case).

**Comment by dokmadeinitaly** [comment] 2022-12-22 08:54
Hi, I’v restarted the (last update 1.2.6) app and send diagnostic report df211a1c-0e82-4adb-9212-deff231f7947:
Now virtual devices lose all configuration and return all to the default room.
I’ve used old HomeyKit app 4 years also with iOS 16.2 Home update and never have this issue, hope you can reply the same problem resolution!

**Comment by robertklep** [comment] 2022-12-22 08:56
@dokmadeinitaly can you give me the names of (some of) your virtual devices so I know what to look for?

**Comment by dokmadeinitaly** [comment] 2022-12-22 10:08
All “Sensore …” (Sensore Cucina, Sensore Ingresso, Sensore Salotto etc…), “Notifica Camera”, “Notifica Cameretta”.
Problem reappeared also after Homey 8.1.1 update.

**Comment by robertklep** [comment] 2022-12-22 10:15
I can see in the diagnostics report that all those devices are added at the proper time, so there's nothing I can do to fix this problem.

Have you upgraded your HomeKit to the new architecture, which Apple introduced with iOS 16.2? Because apparently there were so many problems with it that Apple has stopped providing that option: https://9to5mac.com/2022/12/21/apple-pulls-new-home-app-architecture-in-ios-16-2-as-users-complain-about-homekit-issues/

**Comment by dokmadeinitaly** [comment] 2022-12-22 11:56
Yes i have updated to new architecture but i had no problem with new architecture and old homeykit app.
Yes i use Apple TV and HomePod hub, they are all updated.
Hope you don’t remove old app untill Apple resolve the problem.

**Comment by robertklep** [comment] 2022-12-22 12:10
@dokmadeinitaly are you still running HomeyKit? If not, can you try it to see if it still works? You should be able to run both HomeKitty and HomeyKit next to each other.

**Comment by dokmadeinitaly** [comment] 2022-12-22 12:50
I’m not running homeykit now but yes i’ll try it again, but have a question about it:
Ok, i can run both app next to each other, but wich hub i must use to show devices in HomeKit for this experiment: Homekitty or HomeyKit?
If i use both, i’ll duplicate every virtual devices in HomeKit right?
Then what i must try about?

**Comment by dokmadeinitaly** [comment] 2022-12-22 12:56
Ok, i’m doing, then i must try to reboot app and/or Homey right?

**Comment by robertklep** [comment] 2022-12-22 12:57
@dokmadeinitaly yes, to see if the devices still work correctly with HomeyKit.

**Comment by dokmadeinitaly** [comment] 2022-12-22 13:20
Results:
Reboot homeykit app, all ok, all devices stay to theyr room and config.
Then i rebooted the Homey, same situation all Homeykit app v.d. stay in room and configured but all homekitty app vd device lose room, config etc…
Also i can confirm @raymondwigmore workaronud: if i put a virtual device in HomeKit favorite, they don’t loose config with homekitty app.

**Comment by robertklep** [comment] 2022-12-22 13:29
@dokmadeinitaly actually, from what I understood, the issue that @raymondwigmore had with virtual devices was solved entirely. The only issue that he had was with the Flow Starter device that HomeKitty provides.

**Comment by dokmadeinitaly** [comment] 2022-12-22 13:38
I only saw that if i put a vd in Apple home favorite and restart app and/or homey, i did’nt lose config of that device. Same workaround found by @raymondwigmore.
Maybe the problem is about you suggested in 9to5mac link, strange i don’t have it with homeykit app.

**Comment by robertklep** [comment] 2022-12-22 13:44
@dokmadeinitaly I do think this is a HomeKit issue and not so much a HomeKitty issue, especially if it keeps on working if you favorite the device (which is completely beyond the control of HomeKitty). Since @raymondwigmore was still having issues with not being able to create scenes for no apparent reason, it sounds a lot like iOS is using "old" information for a device that isn't valid anymore.

Another possible fix might be to remove your current HomeKitty home from iOS entirely an then perform a HomeKitty reset (from the app settings), in the hope that that will remove all stored information and basically start over.

**Comment by dokmadeinitaly** [comment] 2022-12-22 14:09
I’ll try and let you now, thakyou for the moment!

**Comment by robertklep** [comment] 2022-12-22 16:08
@raymondwigmore I think that in certain situations HomeKit gets confused, and when it does, it won't recover from it. I had hoped that removing the offending device(s) would solve that issue, but apparently it doesn't (you already tried), which only leaves a full reset.

Not being able to reproduce the issue myself makes it very difficult to debug (and besides, I have no access to the information that iOS stores about its Homes), but the only scenes and automations that I have (not a lot) are only for testing so I don't normally notice if anything goes wrong with them.

**Comment by dokmadeinitaly** [comment] 2023-02-26 11:41
Whith actual version it’s all ok

**Comment by marko0703** [comment] 2023-07-11 19:56
Hi Robert,

I have the same problem. After every Reboot of the Homey I loose almost all devices and configuration in the Homekit. Almost all devices are assigned back to the Default room and I need to reassign again everything to the correct room including other settings like device type. It‘s a problem for all Aeotec, Fibaro, Hue devices. SwitchBot is remaining as well as Nuki. It‘s really annoying to configure again and again over 100 devices.

Can you help on that?

Thank you!
Marko

**Comment by robertklep** [comment] 2023-07-12 04:55
@marko0703 are you running the latest test version? Have you read [this](https://community.homey.app/t/app-pro-homekitty-aka-homeykit-3-0/72824#common-issues-4)?

**Comment by marko0703** [comment] 2023-07-12 13:17
Hi Robert,Now fully understood the problem. Not using the test version. As soon the new version is released I will setup the recommended 10-15 min  delay.Thanks!Marko Von meinem iPhone gesendetAm 12.07.2023 um 06:55 schrieb Robert Klep ***@***.***>:﻿
@marko0703 are you running the latest test version? Have you read this?

**Comment by robertklep** [comment] 2023-07-12 13:25
@marko0703 I would really recommend installing the test version.

**Comment by marko0703** [comment] 2023-07-12 13:27
How can I do this again? Don’t know anymore?!Von meinem iPhone gesendetAm 12.07.2023 um 15:25 schrieb Robert Klep ***@***.***>:﻿
@marko0703 I would really recommend installing the test version.

**Comment by marko0703** [comment] 2023-07-12 17:09
Now working with the test version. I will double check this setting and will see if the problem is ghan solved for me ;-)Thanks!Von meinem iPhone gesendetAm 12.07.2023 um 15:30 schrieb Robert Klep ***@***.***>:﻿
https://homey.app/a/name.klep.homekitty/test/

**Closed** 2024-10-05 06:01 UTC
Labels: needs more info
